services:
  nginx:
    image: nginx:alpine
    ports:
      # Change if the port is already in use. "port_to_use:80"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - pdf_data:/var/www/pdf
    depends_on:
      - frontend
      - backend

  backend:
    build:
      context: ./backend
      target: production
    ports:
      - "8000:8000"
    environment:
      - IN_DOCKER=1
      - OLLAMA_IP=host.docker.internal
      - OLLAMA_PORT=11434
      # Huggingface cache dir config
      - HF_HOME=/root/.cache/huggingface
      # Use POSTGRES_* vars as the single source of truth for DB connection.
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=policybot
      - POSTGRES_PORT=5432
      - RUN_MIGRATIONS=true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - ./backend/.env
    volumes:
      - pdf_data:/app/data
      - huggingface_cache:/root/.cache/huggingface
      - ./backend/logs:/app/logs
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia
    depends_on:
      - postgres
      - qdrant

  model_downloader:
    build:
      context: ./backend
      target: model_downloader
    environment:
      HF_HOME: /root/.cache/huggingface
    volumes:
      - huggingface_cache:/root/.cache/huggingface
    restart: "no"

  frontend:
    build:
      context: ./frontend
      target: production
    ports:
      - "3000:3000"
    depends_on:
      - backend

  postgres:
    image: postgres:17-alpine
    env_file:
      - backend/.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-policybot}
      # - PGDATA=/var/lib/postgresql/18/docker
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init-db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333" # HTTP API
      - "6334:6334" # gRPC API
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped
    environment:
      QDRANT__SERVICE__GRPC_PORT: 6334
      QDRANT__HTTP__PORT: 6333

volumes:
  postgres_data:
    driver: local
  qdrant_data:
    driver: local
  pdf_data:
    driver: local
  huggingface_cache:
    name: policybot_huggingface_cache
    driver: local
